apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gkube-downloads-pvc
  namespace: gkube
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
