---
apiVersion: v1
kind: Service
metadata:
  name: nzbget-svc
  namespace: gkube
spec:
  ports:
    - protocol: TCP
      port: 6789
      targetPort: 6789
  selector:
    app: nzbget
  type: NodePort
