---
apiVersion: v1
kind: Service
metadata:
  name: deluge-svc
  namespace: gkube
spec:
  ports:
    - protocol: TCP
      port: 8112
      targetPort: 8112
    - protocol: TCP
      port: 58846
      targetPort: 58846
    - protocol: TCP
      port: 58946
      targetPort: 58946
    - protocol: UDP
      port: 58946
      targetPort: 58946
  selector:
    app: deluge
  type: NodePort
